name: achieve_takehome_test
description: fetch & display assets from coinbase

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  get_it: ^7.2.0
  logger: ^1.1.0
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  cached_network_image: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  mockito: ^5.0.16
  environment_config: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
